// =====================================================================
// x16clib :: x16/double.c -- 64-bit software floating point (binary64)
// =====================================================================
// THE ARITHMETIC IS THE SAME ASSEMBLY THE OTHER TREES RUN. Oscar64 has
// no `double` type, which means the C entry points below cannot be a
// thin binding the way float.c's are -- but that says nothing about the
// maths, and src_ca65/util/double.s makes no KERNAL call and no
// cross-module call at all. So the body goes in whole, as one global
// __asm block, rather than being reimplemented.
//
// double_body.h and double_defs.h are GENERATED by
// tools/oscar64_double_gen.py. Do not edit them; edit the generator. It
// maps ca65 syntax to Oscar64's, drops the .segment/.export bookkeeping,
// lifts ca65 equates out into #defines (the Oscar64 assembler has none),
// and downgrades the only two 65C02 opcodes the body uses: `bra` becomes
// `jmp`, and `stz` becomes a six-instruction sequence that is flag- and
// A-transparent by construction, because `stz` leaves the flags alone
// and `lda #0 / sta` does not.
//
// WHY THERE IS A DISPATCH PROLOGUE. A label inside a global __asm block
// is not visible from a DIFFERENT __asm block: Oscar64 exposes only the
// block's own name as a callable symbol. Calls WITHIN the block are
// fine, which is exactly why the body drops in whole -- but the C
// entries below cannot `jsr d_load`. So there is one entry point, and a
// selector byte chooses the routine, vectored with the classic RTS
// trick. The argument registers are saved across the dispatch and put
// back immediately before the rts, because the routines take their
// operands in A/X/Y.
//
// ZERO PAGE: four bytes, and they are not optional. The body aliases
// d_ptr = X16_TPTR0 and dstr_ptr = X16_TPTR1 behind (zp),y accesses.
// Oscar64's __zeropage region is nine bytes and other modules here
// already claim eight -- but whole-program compilation strips what a
// program does not call, so those eight are only spent if input.c,
// load.c and pcm.c are all actually used. A program wanting double AND
// all three of those at once will not fit; that is a real limit of this
// target, stated here rather than discovered later.
//
// The X16_P0..P3 argument bytes are NOT zero page: the body only ever
// addresses them absolutely, so they are ordinary globals.
// =====================================================================

#include <x16/double.h>

// The body's pointer scratch. These MUST be zero page -- see above.
__zeropage unsigned char X16_TPTR0[2];
__zeropage unsigned char X16_TPTR1[2];

// The body's argument block. Absolute addressing only, so plain globals.
unsigned char X16_P0, X16_P1, X16_P2, X16_P3;

// The dispatch selector, and the argument registers held across it.
unsigned char x16__d_sel;
unsigned char x16__d_sa, x16__d_sx, x16__d_sy;

// The routine numbers. Order is load-bearing: it indexes d_tbl.
#define D_FN_LOAD       0
#define D_FN_STORE      1
#define D_FN_NEG        2
#define D_FN_ABS        3
#define D_FN_FROM_S16   4
#define D_FN_FROM_S32   5
#define D_FN_TO_S32     6
#define D_FN_CMP        7
#define D_FN_ADD        8
#define D_FN_SUB        9
#define D_FN_MUL        10
#define D_FN_DIV        11
#define D_FN_POW        12
#define D_FN_SQRT       13
#define D_FN_EXP        14
#define D_FN_LN         15
#define D_FN_SIN        16
#define D_FN_COS        17
#define D_FN_TAN        18
#define D_FN_ATAN       19
#define D_FN_SINH       20
#define D_FN_COSH       21
#define D_FN_TANH       22
#define D_FN_FROM_STR   23
#define D_FN_TO_STR     24

// The body's ca65 equates, lifted out by the generator.
#include "double_defs.h"

__asm x16__d_body
{
    // ----------------------------------------------------------------
    // The one entry point. In: x16__d_sel picks the routine, A/X/Y hold
    // its arguments. The pushed address is (target - 1) because rts
    // resumes at the popped address PLUS ONE.
    //
    // The high byte is pushed first so rts pops low (PCL) then high
    // (PCH). Nothing between the pushes and the rts touches the stack,
    // so restoring A/X/Y there is safe -- and it must happen there,
    // since the table lookup needs X for itself.
    //
    // The selected routine's own rts then returns to whoever called
    // x16__d_body: this dispatch adds no frame of its own.
    // ----------------------------------------------------------------
    sta x16__d_sa
    stx x16__d_sx
    sty x16__d_sy

    lda x16__d_sel
    asl
    tax
    lda d_tbl+1,x
    pha
    lda d_tbl,x
    pha

    lda x16__d_sa
    ldx x16__d_sx
    ldy x16__d_sy
    rts

d_tbl:
    byt <(d_load-1), >(d_load-1)
    byt <(d_store-1), >(d_store-1)
    byt <(d_neg-1), >(d_neg-1)
    byt <(d_abs-1), >(d_abs-1)
    byt <(d_from_s16-1), >(d_from_s16-1)
    byt <(d_from_s32-1), >(d_from_s32-1)
    byt <(d_to_s32-1), >(d_to_s32-1)
    byt <(d_cmp-1), >(d_cmp-1)
    byt <(d_add-1), >(d_add-1)
    byt <(d_sub-1), >(d_sub-1)
    byt <(d_mul-1), >(d_mul-1)
    byt <(d_div-1), >(d_div-1)
    byt <(d_pow-1), >(d_pow-1)
    byt <(d_sqrt-1), >(d_sqrt-1)
    byt <(d_exp-1), >(d_exp-1)
    byt <(d_ln-1), >(d_ln-1)
    byt <(d_sin-1), >(d_sin-1)
    byt <(d_cos-1), >(d_cos-1)
    byt <(d_tan-1), >(d_tan-1)
    byt <(d_atan-1), >(d_atan-1)
    byt <(d_sinh-1), >(d_sinh-1)
    byt <(d_cosh-1), >(d_cosh-1)
    byt <(d_tanh-1), >(d_tanh-1)
    byt <(d_from_str-1), >(d_from_str-1)
    byt <(d_to_str-1), >(d_to_str-1)

    // The whole upstream body, verbatim through the converter.
#include "double_body.h"
}

// =====================================================================
// C entry points.
//
// The body's own conventions, from the routine headers in double.s: a
// memory operand arrives as A = low, Y = high (NOT A/X); d_from_s16
// takes A = low, X = high; the 32-bit paths hand values through
// X16_P0..P3; d_cmp answers a signed byte in A; d_to_str answers a
// pointer as A = low, X = high.
// =====================================================================

// --- the accumulator and one memory operand --------------------------
void x16_d_load(const x16_double m) {
    x16__d_sel = D_FN_LOAD;
    __asm {
        lda m
        ldy m+1
        jsr x16__d_body
    }
}

void x16_d_store(x16_double m) {
    x16__d_sel = D_FN_STORE;
    __asm {
        lda m
        ldy m+1
        jsr x16__d_body
    }
}

void x16_d_neg(void) {
    x16__d_sel = D_FN_NEG;
    __asm { jsr x16__d_body }
}

void x16_d_abs(void) {
    x16__d_sel = D_FN_ABS;
    __asm { jsr x16__d_body }
}

// --- integer conversions ---------------------------------------------
void x16_d_from_s16(int v) {
    x16__d_sel = D_FN_FROM_S16;
    __asm {
        lda v
        ldx v+1
        jsr x16__d_body
    }
}

void x16_d_from_s32(long v) {
    x16__d_sel = D_FN_FROM_S32;
    __asm {
        lda v
        sta X16_P0
        lda v+1
        sta X16_P1
        lda v+2
        sta X16_P2
        lda v+3
        sta X16_P3
        jsr x16__d_body
    }
}

// Truncates toward zero; NaN and infinity answer 0 and out-of-range
// values clamp (the body's carry flag is not visible from C).
// The result lands in a MODULE GLOBAL, not a local. Oscar64 puts a
// local on its stack frame, and `sta r` from inside __asm does not
// address that the way it addresses a global -- which is why every test
// that read this function's answer failed while the ones that avoided it
// passed.
static long x16__d_r32;

long x16_d_to_s32(void) {
    x16__d_sel = D_FN_TO_S32;
    __asm {
        jsr x16__d_body
        lda X16_P0
        sta x16__d_r32
        lda X16_P1
        sta x16__d_r32+1
        lda X16_P2
        sta x16__d_r32+2
        lda X16_P3
        sta x16__d_r32+3
    }
    return x16__d_r32;
}

// --- compare ----------------------------------------------------------
// -1 if d_ac < *m, 0 if equal, 1 if greater; a NaN on either side is
// unordered and answers 1.
signed char x16_d_cmp(const x16_double m) {
    x16__d_sel = D_FN_CMP;
    __asm {
        lda m
        ldy m+1
        jsr x16__d_body
        sta accu
    }
}

// --- arithmetic, each against one memory operand ----------------------
void x16_d_add(const x16_double m) {
    x16__d_sel = D_FN_ADD;
    __asm {
        lda m
        ldy m+1
        jsr x16__d_body
    }
}

void x16_d_sub(const x16_double m) {
    x16__d_sel = D_FN_SUB;
    __asm {
        lda m
        ldy m+1
        jsr x16__d_body
    }
}

void x16_d_mul(const x16_double m) {
    x16__d_sel = D_FN_MUL;
    __asm {
        lda m
        ldy m+1
        jsr x16__d_body
    }
}

void x16_d_div(const x16_double m) {
    x16__d_sel = D_FN_DIV;
    __asm {
        lda m
        ldy m+1
        jsr x16__d_body
    }
}

void x16_d_pow(const x16_double m) {
    x16__d_sel = D_FN_POW;
    __asm {
        lda m
        ldy m+1
        jsr x16__d_body
    }
}

// --- the transcendentals, each replacing the accumulator --------------
void x16_d_sqrt(void) { x16__d_sel = D_FN_SQRT; __asm { jsr x16__d_body } }
void x16_d_exp(void)  { x16__d_sel = D_FN_EXP;  __asm { jsr x16__d_body } }
void x16_d_ln(void)   { x16__d_sel = D_FN_LN;   __asm { jsr x16__d_body } }
void x16_d_sin(void)  { x16__d_sel = D_FN_SIN;  __asm { jsr x16__d_body } }
void x16_d_cos(void)  { x16__d_sel = D_FN_COS;  __asm { jsr x16__d_body } }
void x16_d_tan(void)  { x16__d_sel = D_FN_TAN;  __asm { jsr x16__d_body } }
void x16_d_atan(void) { x16__d_sel = D_FN_ATAN; __asm { jsr x16__d_body } }
void x16_d_sinh(void) { x16__d_sel = D_FN_SINH; __asm { jsr x16__d_body } }
void x16_d_cosh(void) { x16__d_sel = D_FN_COSH; __asm { jsr x16__d_body } }
void x16_d_tanh(void) { x16__d_sel = D_FN_TANH; __asm { jsr x16__d_body } }

// --- decimal I/O ------------------------------------------------------
// An explicit length, so a slice of a longer string works without a
// terminator scan.
void x16_d_from_str(const char *s, unsigned char len) {
    x16__d_sel = D_FN_FROM_STR;
    __asm {
        lda s
        ldy s+1
        ldx len
        jsr x16__d_body
    }
}

// The module buffer, which the NEXT CALL OVERWRITES.
// A module global for the same reason x16_d_to_s32 uses one: __asm
// cannot address a C local's stack frame.
static char *x16__d_str;

char *x16_d_to_str(void) {
    x16__d_sel = D_FN_TO_STR;
    __asm {
        jsr x16__d_body
        sta x16__d_str
        stx x16__d_str+1
    }
    return x16__d_str;
}
