// =====================================================================
// x16clib :: x16/double.c -- 64-bit software floating point (binary64)
// =====================================================================
// UNFINISHED, and one specific thing away from working. Not wired into
// <x16/x16.h>, not in the README's supported set, no test suite yet --
// nothing includes double.h, so the committed suite is unaffected.
//
// WHAT WORKS: the whole 3,569-line converted body assembles inside the
// global __asm block below. That was the hard part and it is proven.
//
// WHAT DOES NOT: a label defined inside a global __asm block is NOT
// visible from a DIFFERENT __asm block, so the C entry points below
// cannot `jsr d_load`. (Intra-block calls are fine -- a jsr to a label
// later in the SAME block assembles, which is what made the body drop in
// whole.) Oscar64 makes only the block's own name a callable symbol.
//
// THE FIX, for whoever picks this up: give the blob a dispatch prologue
// and call it as one symbol. Put a selector byte in a global, `jsr
// x16__d_body`, and let the block's first instructions vector on it --
// the classic RTS trick works on NMOS:
//
//      lda sel
//      asl
//      tax
//      lda tbl+1,x
//      pha
//      lda tbl,x
//      pha
//      rts                 ; table entries hold (address - 1)
//
// with a 25-entry table of the d_* routines. Each C function below then
// sets its selector and calls the one symbol. Check first that Oscar64's
// assembler accepts `wor d_load-1` in a table; if not, build the table
// with explicit byte pairs.
// =====================================================================
//
// THE ARITHMETIC IS THE SAME ASSEMBLY THE OTHER TREES RUN. Oscar64 has
// no `double` type, which means the C entry points below cannot be a
// thin binding the way float.c's are -- but it says nothing about the
// maths, and src_ca65/util/double.s turns out to make no KERNAL call and
// no cross-module call at all. So the body goes in whole, as one
// global __asm block, rather than being reimplemented.
//
// double_body.h is GENERATED by tools/oscar64_double_gen.py. Do not edit
// it; edit the generator. It converts ca65 syntax to Oscar64's, drops the
// .segment/.export bookkeeping, and downgrades the only two 65C02
// opcodes the body uses -- `bra` becomes `jmp`, and `stz` becomes a
// six-instruction sequence that is flag- and A-transparent by
// construction, because `stz` leaves the flags alone and `lda #0 / sta`
// does not. (The five 65C02 stack opcodes in the original are all inside
// cc65 entry shims, which are rewritten here rather than converted.)
//
// ZERO PAGE: four bytes, and they are not optional. The body aliases
// d_ptr = X16_TPTR0 and dstr_ptr = X16_TPTR1 behind (zp),y accesses.
// Oscar64's __zeropage region is nine bytes and other modules in this
// library already claim eight of them -- but whole-program compilation
// strips what a program does not call, so those eight are only spent if
// input.c, load.c and pcm.c are all actually used. A program that wants
// double AND all three of those at once will not fit; that is a real
// limit of this target, stated here rather than discovered later.
//
// The X16_P0..P3 argument bytes are NOT zero page: the body only ever
// addresses them absolutely, so they are ordinary globals.
// =====================================================================

#include <x16/double.h>

// The body's pointer scratch. These MUST be zero page -- see above.
__zeropage unsigned char X16_TPTR0[2];
__zeropage unsigned char X16_TPTR1[2];

// The body's argument block. Absolute addressing only, so plain globals.
unsigned char X16_P0, X16_P1, X16_P2, X16_P3;

// The body's ca65 equates, lifted out by the generator: the Oscar64
// assembler has no equate directive, so the preprocessor does it.
#include "double_defs.h"

// The whole upstream body, verbatim through the converter.
__asm x16__d_body
{
#include "double_body.h"
}

// =====================================================================
// C entry points.
//
// The body's own conventions, from the routine headers in double.s:
// a memory operand arrives as A = low, Y = high (NOT A/X); d_from_s16
// takes A = low, X = high; the 32-bit paths hand values through
// X16_P0..P3; d_cmp answers a signed byte in A; d_to_str answers a
// pointer as A = low, X = high.
// =====================================================================

// --- the accumulator and one memory operand --------------------------
void x16_d_load(const x16_double m) {
    __asm {
        lda m
        ldy m+1
        jsr d_load
    }
}

void x16_d_store(x16_double m) {
    __asm {
        lda m
        ldy m+1
        jsr d_store
    }
}

void x16_d_neg(void) { __asm { jsr d_neg } }
void x16_d_abs(void) { __asm { jsr d_abs } }

// --- integer conversions ---------------------------------------------
void x16_d_from_s16(int v) {
    __asm {
        lda v
        ldx v+1
        jsr d_from_s16
    }
}

void x16_d_from_s32(long v) {
    __asm {
        lda v
        sta X16_P0
        lda v+1
        sta X16_P1
        lda v+2
        sta X16_P2
        lda v+3
        sta X16_P3
        jsr d_from_s32
    }
}

// Truncates toward zero; NaN and infinity answer 0 and out-of-range
// values clamp (the body's carry flag is not visible from C).
long x16_d_to_s32(void) {
    long r;

    __asm {
        jsr d_to_s32
        lda X16_P0
        sta r
        lda X16_P1
        sta r+1
        lda X16_P2
        sta r+2
        lda X16_P3
        sta r+3
    }
    return r;
}

// --- compare ----------------------------------------------------------
// -1 if d_ac < *m, 0 if equal, 1 if greater; a NaN on either side is
// unordered and answers 1.
signed char x16_d_cmp(const x16_double m) {
    __asm {
        lda m
        ldy m+1
        jsr d_cmp
        sta accu
    }
}

// --- arithmetic, each against one memory operand ----------------------
void x16_d_add(const x16_double m) {
    __asm {
        lda m
        ldy m+1
        jsr d_add
    }
}

void x16_d_sub(const x16_double m) {
    __asm {
        lda m
        ldy m+1
        jsr d_sub
    }
}

void x16_d_mul(const x16_double m) {
    __asm {
        lda m
        ldy m+1
        jsr d_mul
    }
}

void x16_d_div(const x16_double m) {
    __asm {
        lda m
        ldy m+1
        jsr d_div
    }
}

void x16_d_pow(const x16_double m) {
    __asm {
        lda m
        ldy m+1
        jsr d_pow
    }
}

// --- the transcendentals, each replacing the accumulator --------------
void x16_d_sqrt(void) { __asm { jsr d_sqrt } }
void x16_d_exp(void)  { __asm { jsr d_exp  } }
void x16_d_ln(void)   { __asm { jsr d_ln   } }
void x16_d_sin(void)  { __asm { jsr d_sin  } }
void x16_d_cos(void)  { __asm { jsr d_cos  } }
void x16_d_tan(void)  { __asm { jsr d_tan  } }
void x16_d_atan(void) { __asm { jsr d_atan } }
void x16_d_sinh(void) { __asm { jsr d_sinh } }
void x16_d_cosh(void) { __asm { jsr d_cosh } }
void x16_d_tanh(void) { __asm { jsr d_tanh } }

// --- decimal I/O ------------------------------------------------------
// An explicit length, so a slice of a longer string works without a
// terminator scan.
void x16_d_from_str(const char *s, unsigned char len) {
    __asm {
        lda s
        ldy s+1
        ldx len
        jsr d_from_str
    }
}

// The module buffer, which the NEXT CALL OVERWRITES.
char *x16_d_to_str(void) {
    char *p;

    __asm {
        jsr d_to_str
        sta p
        stx p+1
    }
    return p;
}
