/* GENERATED by tools/oscar64_double_gen.py -- do not edit.
   ca65 `NAME = value` equates, lifted out of the body: the
   Oscar64 assembler has no equate directive, so these are
   substituted by the preprocessor instead. */
#define D_SIZE       8
#define D_ZERO       0
#define D_NORM       1
#define D_INF        2
#define D_NAN        3
#define d_ptr        X16_TPTR0   /* operand pointer (shared scratch) */
#define dstr_ptr     X16_TPTR1   /* d_from_str's string pointer (survives the */
